---
title: Stackbit Azimuth Theme
baseurl: "/"
permalink: "/:title/"
palette: blue
header:
  title: Azimuth
  logo_img: "/images/choe-2.png"
  has_nav: true
  menu:
    actions:
    - label: Case Studies
      url: "/case-studies"
footer:
  logo_img: images/logo_alt.png
  tagline: SaaS theme by Stackbit
  has_nav: true
  nav_title: Company
  has_social: true
  social_title: Community
  has_subscribe: true
  subscribe_title: Subscribe
  subscribe_content: Stay up to date with our latest developments.
  content: "&copy; Choe. All rights reserved."
  links: []
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
- jekyll-menus
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
- ssg-build.sh
- LICENSE.md
- README.md
- netlify.toml
- stackbit-build.sh
- stackbit-pull.js
collections:
  posts:
    permalink: "/posts/:title/"
